scope: patroni_cluster
namespace: /db/
name: patroni_$MASTER_PG_HOST

restapi:
    listen: $MASTER_PG_HOST:8008
    connect_address: $MASTER_PG_HOST:8008

etcd3:
    hosts: $ETCD_HOSTS

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true

    initdb:
    - encoding: UTF8
    - data-checksums

    pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host replication replicator $MASTER_PG_HOST/0 md5
    - host replication replicator $REPLICA_PG_HOST/0 md5
    - host all all 0.0.0.0/0 md5

    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb

postgresql:
    listen: $MASTER_PG_HOST:5432
    connect_address: $MASTER_PG_HOST:5432
    data_dir: /data/patroni
    pgpass: /tmp/pgpass
    authentication:
        replication:
            username: replicator
            password: rep-pass
        superuser:
            username: postgres
            password: postgres
        rewind:  # Has no effect on postgres 10 and lower
            username: rewind_user
            password: rewind_password
    parameters:
        unix_socket_directories: '.'
        shared_preload_libraries: pg_stat_statements

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
