scope: patroni_cluster
namespace: /patroni/
name: patroni_$MASTER_PG_HOST

restapi:
    listen: 0.0.0.0:8008
    connect_address: $MASTER_PG_HOST:8008

consul:
    host: $CONSUL_HOST
    register_service: true

bootstrap:
    dcs:
        ttl: 30
        loop_wait: 10
        retry_timeout: 10
        maximum_lag_on_failover: 1048576
        postgresql:
            use_pg_rewind: true
            parameters:
                max_connections: 550
                max_locks_per_transaction: 512
                max_worker_processes: 27

    initdb:
        - encoding: UTF8
        - data-checksums

    users:
        admin:
            password: admin
            options:
                - createrole
                - createdb

postgresql:
    listen: 0.0.0.0:5432
    connect_address: $MASTER_PG_HOST:5432
    # config_dir: $PGCONFIG
    data_dir: $PGDATA
    pg_hba:
        - host replication replicator 127.0.0.1/32 md5
        - host replication replicator $MASTER_PG_HOST/32 md5
        - host replication replicator $REPLICA_PG_HOST/32 md5
        - host all all 0.0.0.0/0 md5
    authentication:
        replication:
            username: replicator
            password: rep-pass
        superuser:
            username: postgres
            password: postgres
        rewind:  # Has no effect on postgres 10 and lower
            username: rewind_user
            password: rewind_password
    parameters:
        unix_socket_directories: '.'
        shared_preload_libraries: pg_stat_statements

tags:
    nofailover: false
    noloadbalance: false
    clonefrom: false
    nosync: false
